name: Python setup + pytest (Poetry optional)
description: Set up Python, install deps, and optionally run pytest.
inputs:
  python:
    description: Python version (e.g. 3.11)
    required: true
  pytest-path:
    description: "Path passed to pytest (e.g. tests/unit). If empty, caller runs pytest."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}

    - name: Install Poetry
      shell: bash
      run: python -m pip install -U pip poetry

    - name: Restore caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pypoetry
        key: ${{ runner.os }}-py${{ inputs.python }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-py${{ inputs.python }}-

    - name: Install deps
      shell: bash
      run: python -m poetry install

    - name: Run pytest (optional)
      if: ${{ inputs.pytest-path != '' }}
      shell: bash
      run: python -m poetry run pytest "${{ inputs.pytest-path }}" -q
