name: Python setup + pytest (Poetry optional)
description: Set up Python, install deps, and optionally run pytest.
inputs:
  python:
    description: Python version (e.g. 3.11)
    required: true
  pytest-path:
    description: "Path passed to pytest (e.g. tests/unit). If empty, caller runs pytest."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}
        cache: poetry
        cache-dependency-path: |
          **/pyproject.toml
          **/poetry.lock
          **/requirements*.txt

    - name: Install Poetry
      shell: bash
      run: python -m pip install -U pip poetry

    - name: Install deps
      shell: bash
      run: poetry install

    - name: Run pytest (optional)
      if: ${{ inputs.pytest-path != '' }}
      shell: bash
      run: poetry run pytest "${{ inputs.pytest-path }}" -q
