name: Build and Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9","3.10","3.11","3.12","3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry
        with:
          python: ${{ matrix.python }}
          use-poetry: "false"
          pytest-path: tests/unit

  test_integration:
    needs: test_unit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9","3.10","3.11","3.12","3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry
        with:
          python: ${{ matrix.python }}
          use-poetry: "false"
          pytest-path: tests/integration

  build:
    needs:
      - test_unit
      - test_integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock
            **/requirements*.txt

      - name: Install build tool
        run: pip install -U build

      - name: Build distribution
        run: python -m build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.9 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/poetry.lock
            **/requirements*.txt

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Twine check
        run: |
          pip install -U twine
          twine check dist/*
